/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luopingelec_smarthome_LPMP4Encoder */

#ifndef _Included_com_luopingelec_smarthome_jniLPMP4Encoder
#define _Included_com_luopingelec_smarthome_jniLPMP4Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luopingelec_smarthome_LPMP4Encoder
 * Method:    createMP4Encoder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_luopingelec_smarthome_LPMP4Encoder_createMP4Encoder
  (JNIEnv *, jclass);

/*
 * Class:     com_luopingelec_smarthome_LPMP4Encoder
 * Method:    destroyMP4Encoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luopingelec_smarthome_LPMP4Encoder_destroyMP4Encoder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luopingelec_smarthome_LPMP4Encoder
 * Method:    createFile
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luopingelec_smarthome_LPMP4Encoder_createFile
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_luopingelec_smarthome_LPMP4Encoder
 * Method:    closeFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luopingelec_smarthome_LPMP4Encoder_closeFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luopingelec_smarthome_LPMP4Encoder
 * Method:    writeH264Data
 * Signature: (J[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_luopingelec_smarthome_LPMP4Encoder_writeH264Data
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
